#!/usr/bin/env bash
#
# One-shot local dev bootstrap for Marquee.
#
#   npm run dev              # backend + app
#   npm run dev -- --no-app  # just bring the backend up (skip Expo)
#
# Brings up the Supabase backend (Postgres/PostGIS, auth, edge functions) with
# migrations + seed data, writes the app's .env from the local credentials, and
# launches Expo. Safe to re-run: each step is idempotent.

set -euo pipefail

# Run from the repo root regardless of where this is invoked from.
cd "$(dirname "$0")/.."

RUN_APP=1
for arg in "$@"; do
  case "$arg" in
    --no-app) RUN_APP=0 ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

info()  { printf '\033[1;34m▶\033[0m %s\n' "$1"; }
warn()  { printf '\033[1;33m!\033[0m %s\n' "$1"; }
die()   { printf '\033[1;31m✗\033[0m %s\n' "$1" >&2; exit 1; }

# 1. Node dependencies -------------------------------------------------------
if [ ! -d node_modules ]; then
  info "Installing npm dependencies…"
  npm install
fi

# 2. Supabase CLI ------------------------------------------------------------
if ! command -v supabase >/dev/null 2>&1; then
  warn "Supabase CLI not found."
  if command -v brew >/dev/null 2>&1; then
    read -r -p "Install it now with Homebrew? [y/N] " ans
    if [[ "$ans" =~ ^[Yy]$ ]]; then
      brew install supabase/tap/supabase
    else
      die "Install it manually, then re-run: https://supabase.com/docs/guides/cli"
    fi
  else
    die "Install the Supabase CLI, then re-run: https://supabase.com/docs/guides/cli"
  fi
fi

# 3. Docker daemon -----------------------------------------------------------
if ! docker info >/dev/null 2>&1; then
  warn "Docker isn't running. Trying to start Docker Desktop…"
  open -a Docker >/dev/null 2>&1 || die "Couldn't launch Docker. Start it manually and re-run."
  printf 'Waiting for Docker'
  for _ in $(seq 1 60); do
    if docker info >/dev/null 2>&1; then printf ' ready.\n'; break; fi
    printf '.'; sleep 2
  done
  docker info >/dev/null 2>&1 || die "Docker still isn't ready. Start Docker Desktop and re-run."
fi

# 4. Backend -----------------------------------------------------------------
info "Starting Supabase (applies migrations + seed data; first run pulls images)…"
supabase start

# 5. App .env from local credentials ----------------------------------------
info "Writing .env from local Supabase credentials…"
# `supabase status -o env` emits shell assignments (API_URL, ANON_KEY, …).
eval "$(supabase status -o env)"
: "${API_URL:?Could not read API_URL from supabase status}"
: "${ANON_KEY:?Could not read ANON_KEY from supabase status}"
cat > .env <<EOF
# Auto-generated by scripts/dev.sh — local Supabase credentials.
EXPO_PUBLIC_SUPABASE_URL=$API_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EOF

# 6. App ---------------------------------------------------------------------
if [ "$RUN_APP" -eq 1 ]; then
  info "Launching Expo — press i (iOS), a (Android), or w (web)."
  npx expo start
else
  info "Backend is up. .env written. Start the app with: npx expo start"
fi
